# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
